MULL_DICT = {"seven":0,"six":1,"five":2,"four":3,"three":4,"two":5,"one":6,"zero":7}
SPLIT_CARDS = {
    'Alive': 'Alive/Well',
    'Well': 'Alive/Well',
    'Appeal': 'Appeal/Authority',
    'Authority': 'Appeal/Authority',
    'Armed': 'Armed/Dangerous',
    'Dangerous': 'Armed/Dangerous',
    'Assault': 'Assault/Battery',
    'Battery': 'Assault/Battery',
    'Assure': 'Assure/Assemble',
    'Assemble': 'Assure/Assemble',
    'Beck': 'Beck/Call',
    'Call': 'Beck/Call',
    'Bedeck': 'Bedeck/Bedazzle',
    'Bedazzle': 'Bedeck/Bedazzle',
    'Boom': 'Boom/Bust',
    'Bust': 'Boom/Bust',
    'Bound': 'Bound/Determined',
    'Determined': 'Bound/Determined',
    'Breaking': 'Breaking/Entering',
    'Entering': 'Breaking/Entering',
    'Carnival': 'Carnival/Carnage',
    'Carnage': 'Carnival/Carnage',
    'Catch': 'Catch/Release',
    'Release': 'Catch/Release',
    'Claim': 'Claim/Fame',
    'Fame': 'Claim/Fame',
    'Collision': 'Collision/Colossus',
    'Colossus': 'Collision/Colossus',
    'Commit': 'Commit/Memory',
    'Memory': 'Commit/Memory',
    'Connive': 'Connive/Concoct',
    'Concoct': 'Connive/Concoct',
    'Consecrate': 'Consecrate/Consume',
    'Consume': 'Consecrate/Consume',
    'Consign': 'Consign/Oblivion',
    'Oblivion': 'Consign/Oblivion',
    'Crime': 'Crime/Punishment',
    'Punishment': 'Crime/Punishment',
    'Cut': 'Cut/Ribbons',
    'Ribbons': 'Cut/Ribbons',
    'Dead': 'Dead/Gone',
    'Gone': 'Dead/Gone',
    'Depose': 'Depose/Deploy',
    'Deploy': 'Depose/Deploy',
    'Destined': 'Destined/Lead',
    'Lead': 'Destined/Lead',
    'Discovery': 'Discovery/Dispersal',
    'Dispersal': 'Discovery/Dispersal',
    'Down': 'Down/Dirty',
    'Dirty': 'Down/Dirty',
    'Driven': 'Driven/Despair',
    'Despair': 'Driven/Despair',
    'Dusk': 'Dusk/Dawn',
    'Dawn': 'Dusk/Dawn',
    'Expansion': 'Expansion/Explosion',
    'Explosion': 'Expansion/Explosion',
    'Failure': 'Failure/Comply',
    'Comply': 'Failure/Comply',
    'Far': 'Far/Away',
    'Away': 'Far/Away',
    'Farm': 'Farm/Market',
    'Market': 'Farm/Market',
    'Fast': 'Fast/Furious',
    'Furious': 'Fast/Furious',
    'Find': 'Find/Finality',
    'Finality': 'Find/Finality',
    'Fire': 'Fire/Ice',
    'Ice': 'Fire/Ice',
    'Flesh': 'Flesh/Blood',
    'Blood': 'Flesh/Blood',
    'Flower': 'Flower/Flourish',
    'Flourish': 'Flower/Flourish',
    'Give': 'Give/Take',
    'Take': 'Give/Take',
    'Grind': 'Grind/Dust',
    'Dust': 'Grind/Dust',
    'Heaven': 'Heaven/Earth',
    'Earth': 'Heaven/Earth',
    'Hide': 'Hide/Seek',
    'Seek': 'Hide/Seek',
    'Hit': 'Hit/Run',
    'Run': 'Hit/Run',
    'Illusion': 'Illusion/Reality',
    'Reality': 'Illusion/Reality',
    'Incubation': 'Incubation/Incongruity',
    'Incongruity': 'Incubation/Incongruity',
    'Insult': 'Insult/Injury',
    'Injury': 'Insult/Injury',
    'Integrity': 'Integrity/Intervention',
    'Intervention': 'Integrity/Intervention',
    'Invert': 'Invert/Invent',
    'Invent': 'Invert/Invent',
    'Leave': 'Leave/Chance',
    'Chance': 'Leave/Chance',
    'Life': 'Life/Death',
    'Death': 'Life/Death',
    'Mouth': 'Mouth/Feed',
    'Feed': 'Mouth/Feed',
    'Never': 'Never/Return',
    'Return': 'Never/Return',
    'Night': 'Night/Day',
    'Day': 'Night/Day',
    'Odds': 'Odds/Ends',
    'Ends': 'Odds/Ends',
    'Onward': 'Onward/Victory',
    'Victory': 'Onward/Victory',
    'Order': 'Order/Chaos',
    'Chaos': 'Order/Chaos',
    'Pain': 'Pain/Suffering',
    'Suffering': 'Pain/Suffering',
    'Prepare': 'Prepare/Fight',
    'Fight': 'Prepare/Fight',
    'Profit': 'Profit/Loss',
    'Loss': 'Profit/Loss',
    'Protect': 'Protect/Serve',
    'Serve': 'Protect/Serve',
    'Pure': 'Pure/Simple',
    'Simple': 'Pure/Simple',
    'Rags': 'Rags/Riches',
    'Riches': 'Rags/Riches',
    'Ready': 'Ready/Willing',
    'Willing': 'Ready/Willing',
    'Reason': 'Reason/Believe',
    'Believe': 'Reason/Believe',
    'Reduce': 'Reduce/Rubble',
    'Rubble': 'Reduce/Rubble',
    'Refuse': 'Refuse/Cooperate',
    'Cooperate': 'Refuse/Cooperate',
    'Repudiate': 'Repudiate/Replicate',
    'Replicate': 'Repudiate/Replicate',
    'Research': 'Research/Development',
    'Development': 'Research/Development',
    'Response': 'Response/Resurgence',
    'Resurgence': 'Response/Resurgence',
    'Revival': 'Revival/Revenge',
    'Revenge': 'Revival/Revenge',
    'Rise': 'Rise/Fall',
    'Fall': 'Rise/Fall',
    'Road': 'Road/Ruin',
    'Ruin': 'Road/Ruin',
    'Rough': 'Rough/Tumble',
    'Tumble': 'Rough/Tumble',
    'Said': 'Said/Done',
    'Done': 'Said/Done',
    'Spite': 'Spite/Malice',
    'Malice': 'Spite/Malice',
    'Spring': 'Spring/Mind',
    'Mind': 'Spring/Mind',
    'Stand': 'Stand/Deliver',
    'Deliver': 'Stand/Deliver',
    'Start': 'Start/Finish',
    'Finish': 'Start/Finish',
    'Status': 'Status/Statue',
    'Statue': 'Status/Statue',
    'Struggle': 'Struggle/Survive',
    'Survive': 'Struggle/Survive',
    'Supply': 'Supply/Demand',
    'Demand': 'Supply/Demand',
    'Thrash': 'Thrash/Threat',
    'Threat': 'Thrash/Threat',
    'Toil': 'Toil/Trouble',
    'Trouble': 'Toil/Trouble',
    'Trial': 'Trial/Error',
    'Error': 'Trial/Error',
    'Turn': 'Turn/Burn',
    'Burn': 'Turn/Burn',
    'Warrant': 'Warrant/Warden',
    'Warden': 'Warrant/Warden',
    'Wax': 'Wax/Wane',
    'Wane': 'Wax/Wane',
    'Wear': 'Wear/Tear',
    'Tear': 'Wear/Tear'
    }
ADVENTURE_CARDS = {
    "Bring to Life" : "Animating Faerie",
    "Dizzying Swoop" : "Ardenvale Tactician",
    "Fertile Footsteps" : "Beanstalk Giant",
    "Stomp" : "Bonecrusher Giant",
    "Petty Theft" : "Brazen Borrower",
    "Treats to Share" : "Curious Pair",
    "Battle Display" : "Embereth Shieldbreaker",
    "Granted" : "Fae of Wishes",
    "Gift of the Fae" : "Faerie Guidemother",
    "Welcome Home" : "Flaxen Intruder",
    "Profane Insight" : "Foulmire Knight",
    "Shield's Might" : "Garenbrig Carver",
    "Chop Down" : "Giant Killer",
    "Mesmeric Glare" : "Hypnotic Sprite",
    "Rider in Need" : "Lonesome Unicorn",
    "Heart's Desire" : "Lovestruck Beast",
    "Haggle" : "Merchant of the Vale",
    "Venture Deeper" : "Merfolk Secretkeeper",
    "Swift End" : "Murderous Rider",
    "Bring Back" : "Oakhame Ranger",
    "Alter Fate" : "Order of Midnight",
    "Rage of Winter" : "Queen of Ice",
    "Cast Off" : "Realm-Cloaked Giant",
    "Harvest Fear" : "Reaper of Night",
    "Boulder Rush" : "Rimrock Knight",
    "Seasonal Ritual" : "Rosethorn Acolyte",
    "Usher to Safety" : "Shepherd of the Flock",
    "On Alert" : "Silverflame Squire",
    "Curry Favor" : "Smitten Swordmaster",
    "Oaken Boon" : "Tuinvale Treefolk"
    }
DRAFT_FORMATS = [
    "VMA x3",
    "VOW x3",
    "MID x3",
    "AFR x3",
    "MH2 x3",
    "STX x3",
    "TSR x3",
    "KHM x3",
    "ZNR x3",
    "2XM x3",
    "M21 x3",
    "IKO x3",
    "THB x3",
    "ELD x3",
    "M20 x3",
    "MH1 x3",
    "WAR x3",
    "RNA x3",
    "UMA x3",
    "GRN x3",
    "M19 x3",
    "DOM x3",
    "A25 x3",
    "RIX x3",
    "IMA x3",
    "XLN x3",
    "HOU x3",
    "AKH x3",
    "MM3 x3",
    "AER x3",
    "Other Booster Draft"]
SEALED_FORMATS=[
    "VOW x6",
    "MID x6",
    "AFR x6",
    "MH2 x6",
    "STX x6",
    "TSR x6",
    "KHM x6",
    "ZNR x6",
    "2XM x6",
    "M21 x6",
    "IKO x6",
    "THB x6",
    "ELD x6",
    "M20 x6",
    "MH1 x6",
    "WAR x6",
    "RNA x6",
    "UMA x6",
    "GRN x6",
    "M19 x6",
    "DOM x6",
    "A25 x6",
    "RIX x6",
    "IMA x6",
    "XLN x6",
    "HOU x6",
    "AKH x6",
    "MM3 x6",
    "AER x6",
    "Other Sealed"]

LIMITED_FORMATS =  [
    "Booster Draft",
    "Sealed Deck",
    "Cube"]
CONSTRUCTED_FORMATS =  [
    "Vintage",
    "Legacy",
    "Modern",
    "Standard",
    "Pioneer",
    "Pauper",
    "Other Constructed"]
CUBE_FORMATS = [
    "Cube-Other",
    "Vintage Cube",
    "Legacy Cube",
    "Modern Cube"]

CONSTRUCTED_PLAY_TYPES = [
    "League",
    "Preliminary",
    "Challenge",
    "Premier Constructed",
    "2-Man",
    "Practice",
    "Open Play BO1"]
DRAFT_PLAY_TYPES = [
    "Draft League",
    "Swiss Draft",
    "Elimination Draft"]
SEALED_PLAY_TYPES = [
    "Friendly Sealed League",
    "Competitive Sealed League",
    "Premier Sealed"]

ARCHETYPES = [
    "Aggro",
    "Midrange",
    "Control",
    "Combo",
    "Prison",
    "Tempo",
    "Ramp",
    "Rogue"
    ]

CARDS_DRAWN_DICT = {"zero":0,"a":1,"two":2,"three":3,"four":4,"five":5,"six":6,"seven":7}

MATCHES_HEADER = [
    "Match_ID",
    "Draft_ID",
    "P1",
    "P1_Arch",
    "P1_Subarch",
    "P2",
    "P2_Arch",
    "P2_Subarch",
    "P1_Roll",
    "P2_Roll",
    "Roll_Winner",
    "P1_Wins",
    "P2_Wins",
    "Match_Winner",
    "Format",
    "Limited_Format",
    "Match_Type",
    "Date"
    ]

PLAYS_HEADER = [
    "Match_ID",
    "Game_Num",
    "Play_Num",
    "Turn_Num",
    "Casting_Player",
    "Action",
    "Primary_Card",
    "Target1",
    "Target2",
    "Target3",
    "Opp_Target",
    "Self_Target",
    "Cards_Drawn",
    "Attackers",
    "Active_Player",
    "Nonactive_Player"
    ]

DRAFT_HEADER = [
    "Draft_ID",
    "Hero",
    "Player_2",
    "Player_3",
    "Player_4",
    "Player_5",
    "Player_6",
    "Player_7",
    "Player_8",
    "Match_Wins",
    "Match_Losses",
    "Format",
    "Date"]

PICK_HEADER = [
    "Draft_ID",
    "Card",
    "Pack_Num",
    "Pick_Num",
    "Pick_Ovr",
    "Avail_1",
    "Avail_2",
    "Avail_3",
    "Avail_4",
    "Avail_5",
    "Avail_6",
    "Avail_7",
    "Avail_8",
    "Avail_9",
    "Avail_10",
    "Avail_11",
    "Avail_12",
    "Avail_13",
    "Avail_14"
    ]

GAME_HEADER = [
    "Match_ID",
    "P1",
    "P2",
    "Game_Num",
    "PD_Selector",
    "PD_Choice",
    "On_Play",
    "On_Draw",
    "P1_Mulls",
    "P2_Mulls",
    "Turns",
    "Game_Winner"]

HEADERS = {
    'Picks': PICK_HEADER,
    'Drafts': DRAFT_HEADER,
    'Plays': PLAYS_HEADER,
    'Games': GAME_HEADER,
    'Matches': MATCHES_HEADER
}